<?php

namespace Gift\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryGiftRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryGiftRepository extends EntityRepository
{
}
