<?php

namespace Gift\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoverRepository extends EntityRepository
{
}
